# Generated by Django 5.2.5 on 2025-09-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_register_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='image',
        ),
        migrations.AddField(
            model_name='register',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='uploads/'),
        ),
    ]
