# Generated by Django 5.2.5 on 2025-09-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_register_image_register_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='uploads/')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roomname', models.CharField(max_length=50)),
                ('roomrating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('bed', models.PositiveIntegerField()),
                ('bath', models.PositiveIntegerField()),
                ('wifi', models.BooleanField(default=False)),
                ('desc', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
