# Generated by Django 5.2.5 on 2025-09-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_addroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addroom',
            name='image',
        ),
        migrations.AddField(
            model_name='addroom',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='uploads/'),
        ),
    ]
