# Generated by Django 5.2.5 on 2025-09-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_addroom_image_addroom_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='roomrating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
