# Generated by Django 5.2.5 on 2025-09-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_addroom_roomrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addroom',
            old_name='roomrating',
            new_name='roomratting',
        ),
    ]
