# Generated by Django 5.2.5 on 2025-09-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_roomrating_addroom_roomratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='file',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='uploads/'),
        ),
    ]
